# Ultralytics YOLO üöÄ, AGPL-3.0 license

site_name: Ultralytics YOLOv8 Docs
site_description: Explore Ultralytics YOLOv8, a cutting-edge real-time object detection and image segmentation model for various applications and hardware platforms.
site_url: https://docs.ultralytics.com
site_author: Ultralytics
repo_url: https://github.com/ultralytics/ultralytics
edit_uri: https://github.com/ultralytics/ultralytics/tree/main/docs/en/
repo_name: ultralytics/ultralytics
remote_name: https://github.com/ultralytics/docs
docs_dir: "docs/en/" # where to find the markdown files
site_dir: "site/" # where to publish to

theme:
  name: material
  language: en
  logo: https://github.com/ultralytics/assets/raw/main/logo/Ultralytics_Logotype_Reverse.svg
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections  # navigation.expand or navigation.sections
    - content.tabs.link # all code tabs change simultaneously

# Primary navigation ---------------------------------------------------------------------------------------------------
nav:
  - Home:
      - Home: index.md
      - Quickstart: quickstart.md
      - Modes:
          - modes/index.md
          - Train: modes/train.md
          - Val: modes/val.md
          - Predict: modes/predict.md
          - Export: modes/export.md
          - Track: modes/track.md
          - Benchmark: modes/benchmark.md
      - Tasks:
          - tasks/index.md
          - Detect: tasks/detect.md
          - Segment: tasks/segment.md
          - Classify: tasks/classify.md
          - Pose: tasks/pose.md
          - OBB: tasks/obb.md
      - Models:
          - models/index.md
      - Datasets:
          - datasets/index.md
      - Guides:
          - guides/index.md
      - NEW üöÄ Explorer:
          - datasets/explorer/index.md
      - Languages:
          - üá¨üáß&nbsp English: https://ultralytics.com/docs/
          - üá®üá≥&nbsp ÁÆÄ‰Ωì‰∏≠Êñá: https://docs.ultralytics.com/zh/
          - üá∞üá∑&nbsp ÌïúÍµ≠Ïñ¥: https://docs.ultralytics.com/ko/
          - üáØüáµ&nbsp Êó•Êú¨Ë™û: https://docs.ultralytics.com/ja/
          - üá∑üá∫&nbsp –†—É—Å—Å–∫–∏–π: https://docs.ultralytics.com/ru/
          - üá©üá™&nbsp Deutsch: https://docs.ultralytics.com/de/
          - üá´üá∑&nbsp Fran√ßais: https://docs.ultralytics.com/fr/
          - üá™üá∏&nbsp Espa√±ol: https://docs.ultralytics.com/es/
          - üáµüáπ&nbsp Portugu√™s: https://docs.ultralytics.com/pt/
          - üáÆüá≥&nbsp ‡§π‡§ø‡§®‡•ç‡§¶‡•Ä: https://docs.ultralytics.com/hi/
          - üá∏üá¶&nbsp ÿßŸÑÿπÿ±ÿ®Ÿäÿ©: https://docs.ultralytics.com/ar/
  - Quickstart:
      - quickstart.md
      - Usage:
          - CLI: usage/cli.md
          - Python: usage/python.md
          - Callbacks: usage/callbacks.md
          - Configuration: usage/cfg.md
          - Advanced Customization: usage/engine.md
  - Modes:
      - modes/index.md
      - Train: modes/train.md
      - Val: modes/val.md
      - Predict: modes/predict.md
      - Export: modes/export.md
      - Track: modes/track.md
      - Benchmark: modes/benchmark.md
  - Tasks:
      - tasks/index.md
      - Detect: tasks/detect.md
      - Segment: tasks/segment.md
      - Classify: tasks/classify.md
      - Pose: tasks/pose.md
      - OBB: tasks/obb.md
  - Models:
      - models/index.md
      - YOLOv3: models/yolov3.md
      - YOLOv4: models/yolov4.md
      - YOLOv5: models/yolov5.md
      - YOLOv6: models/yolov6.md
      - YOLOv7: models/yolov7.md
      - YOLOv8: models/yolov8.md
      - SAM (Segment Anything Model): models/sam.md
      - MobileSAM (Mobile Segment Anything Model): models/mobile-sam.md
      - FastSAM (Fast Segment Anything Model): models/fast-sam.md
      - YOLO-NAS (Neural Architecture Search): models/yolo-nas.md
      - RT-DETR (Realtime Detection Transformer): models/rtdetr.md
  - Datasets:
      - datasets/index.md
      - NEW üöÄ Explorer:
          - datasets/explorer/index.md
          - Explorer API: datasets/explorer/api.md
          - Explorer Dashboard: datasets/explorer/dashboard.md
          - VOC Exploration Example: datasets/explorer/explorer.ipynb
      - Detection:
          - datasets/detect/index.md
          - Argoverse: datasets/detect/argoverse.md
          - COCO: datasets/detect/coco.md
          - COCO8: datasets/detect/coco8.md
          - GlobalWheat2020: datasets/detect/globalwheat2020.md
          - Objects365: datasets/detect/objects365.md
          - OpenImagesV7: datasets/detect/open-images-v7.md
          - SKU-110K: datasets/detect/sku-110k.md
          - VisDrone: datasets/detect/visdrone.md
          - VOC: datasets/detect/voc.md
          - xView: datasets/detect/xview.md
          - Roboflow 100: datasets/detect/roboflow-100.md
      - Segmentation:
          - datasets/segment/index.md
          - COCO: datasets/segment/coco.md
          - COCO8-seg: datasets/segment/coco8-seg.md
          - Crack-seg: datasets/segment/crack-seg.md
          - Carparts-seg: datasets/segment/carparts-seg.md
          - Package-seg: datasets/segment/package-seg.md
      - Pose:
          - datasets/pose/index.md
          - COCO: datasets/pose/coco.md
          - COCO8-pose: datasets/pose/coco8-pose.md
          - Tiger-pose: datasets/pose/tiger-pose.md
      - Classification:
          - datasets/classify/index.md
          - Caltech 101: datasets/classify/caltech101.md
          - Caltech 256: datasets/classify/caltech256.md
          - CIFAR-10: datasets/classify/cifar10.md
          - CIFAR-100: datasets/classify/cifar100.md
          - Fashion-MNIST: datasets/classify/fashion-mnist.md
          - ImageNet: datasets/classify/imagenet.md
          - ImageNet-10: datasets/classify/imagenet10.md
          - Imagenette: datasets/classify/imagenette.md
          - Imagewoof: datasets/classify/imagewoof.md
          - MNIST: datasets/classify/mnist.md
      - Oriented Bounding Boxes (OBB):
          - datasets/obb/index.md
          - DOTAv2: datasets/obb/dota-v2.md
          - DOTA8: datasets/obb/dota8.md
      - Multi-Object Tracking:
          - datasets/track/index.md
  - NEW üöÄ Explorer:
      - datasets/explorer/index.md
      - Explorer API: datasets/explorer/api.md
      - Explorer Dashboard Demo: datasets/explorer/dashboard.md
      - VOC Exploration Example: datasets/explorer/explorer.ipynb
  - Guides:
      - guides/index.md
      - YOLO Common Issues: guides/yolo-common-issues.md
      - YOLO Performance Metrics: guides/yolo-performance-metrics.md
      - YOLO Thread-Safe Inference: guides/yolo-thread-safe-inference.md
      - Model Deployment Options: guides/model-deployment-options.md
      - K-Fold Cross Validation: guides/kfold-cross-validation.md
      - Hyperparameter Tuning: guides/hyperparameter-tuning.md
      - SAHI Tiled Inference: guides/sahi-tiled-inference.md
      - AzureML Quickstart: guides/azureml-quickstart.md
      - Conda Quickstart: guides/conda-quickstart.md
      - Docker Quickstart: guides/docker-quickstart.md
      - Raspberry Pi: guides/raspberry-pi.md
      - Triton Inference Server: guides/triton-inference-server.md
      - Isolating Segmentation Objects: guides/isolating-segmentation-objects.md
      - Real-World Projects:
          - Object Counting: guides/object-counting.md
          - Object Cropping: guides/object-cropping.md
          - Object Blurring: guides/object-blurring.md
          - Workouts Monitoring: guides/workouts-monitoring.md
          - Objects Counting in Regions: guides/region-counting.md
          - Security Alarm System: guides/security-alarm-system.md
          - Heatmaps: guides/heatmaps.md
          - Instance Segmentation with Object Tracking: guides/instance-segmentation-and-tracking.md
          - VisionEye Mapping: guides/vision-eye.md
          - Speed Estimation: guides/speed-estimation.md
          - Distance Calculation: guides/distance-calculation.md
      - YOLOv5:
          - yolov5/index.md
          - Quickstart: yolov5/quickstart_tutorial.md
          - Environments:
              - Amazon Web Services (AWS): yolov5/environments/aws_quickstart_tutorial.md
              - Google Cloud (GCP): yolov5/environments/google_cloud_quickstart_tutorial.md
              - AzureML: yolov5/environments/azureml_quickstart_tutorial.md
              - Docker Image: yolov5/environments/docker_image_quickstart_tutorial.md
          - Tutorials:
              - Train Custom Data: yolov5/tutorials/train_custom_data.md
              - Tips for Best Training Results: yolov5/tutorials/tips_for_best_training_results.md
              - Multi-GPU Training: yolov5/tutorials/multi_gpu_training.md
              - PyTorch Hub: yolov5/tutorials/pytorch_hub_model_loading.md
              - TFLite, ONNX, CoreML, TensorRT Export: yolov5/tutorials/model_export.md
              - NVIDIA Jetson Nano Deployment: yolov5/tutorials/running_on_jetson_nano.md
              - Test-Time Augmentation (TTA): yolov5/tutorials/test_time_augmentation.md
              - Model Ensembling: yolov5/tutorials/model_ensembling.md
              - Pruning/Sparsity Tutorial: yolov5/tutorials/model_pruning_and_sparsity.md
              - Hyperparameter evolution: yolov5/tutorials/hyperparameter_evolution.md
              - Transfer learning with frozen layers: yolov5/tutorials/transfer_learning_with_frozen_layers.md
              - Architecture Summary: yolov5/tutorials/architecture_description.md
              - Roboflow Datasets: yolov5/tutorials/roboflow_datasets_integration.md
              - Neural Magic's DeepSparse: yolov5/tutorials/neural_magic_pruning_quantization.md
              - Comet Logging: yolov5/tutorials/comet_logging_integration.md
              - Clearml Logging: yolov5/tutorials/clearml_logging_integration.md
  - Integrations:
      - integrations/index.md
      - Comet ML: integrations/comet.md
      - OpenVINO: integrations/openvino.md
      - ONNX: integrations/onnx.md
      - TensorRT: integrations/tensorrt.md
      - CoreML: integrations/coreml.md
      - Ray Tune: integrations/ray-tune.md
      - Roboflow: integrations/roboflow.md
      - MLflow: integrations/mlflow.md
      - ClearML: integrations/clearml.md
      - DVC: integrations/dvc.md
      - Weights & Biases: integrations/weights-biases.md
      - Neural Magic: integrations/neural-magic.md
      - Gradio: integrations/gradio.md
      - TensorBoard: integrations/tensorboard.md
      - Amazon SageMaker: integrations/amazon-sagemaker.md
  - HUB:
      - Cloud:
          - hub/index.md
          - Quickstart: hub/quickstart.md
          - Datasets: hub/datasets.md
          - Projects: hub/projects.md
          - Models: hub/models.md
          - Integrations: hub/integrations.md
          - Inference API: hub/inference-api.md
      - On-Premise:
          - hub/on-premise/index.md
      - App:
          - hub/app/index.md
          - iOS: hub/app/ios.md
          - Android: hub/app/android.md
      - REST API:
          - hub/api/index.md

  - Reference:
      - cfg:
          - __init__: reference/cfg/__init__.md
      - data:
          - annotator: reference/data/annotator.md
          - augment: reference/data/augment.md
          - base: reference/data/base.md
          - build: reference/data/build.md
          - converter: reference/data/converter.md
          - dataset: reference/data/dataset.md
          - explorer:
              - explorer: reference/data/explorer/explorer.md
              - gui:
                  - dash: reference/data/explorer/gui/dash.md
              - utils: reference/data/explorer/utils.md
          - loaders: reference/data/loaders.md
          - split_dota: reference/data/split_dota.md
          - utils: reference/data/utils.md
      - engine:
          - exporter: reference/engine/exporter.md
          - model: reference/engine/model.md
          - predictor: reference/engine/predictor.md
          - results: reference/engine/results.md
          - trainer: reference/engine/trainer.md
          - tuner: reference/engine/tuner.md
          - validator: reference/engine/validator.md
      - hub:
          - __init__: reference/hub/__init__.md
          - auth: reference/hub/auth.md
          - session: reference/hub/session.md
          - utils: reference/hub/utils.md
      - models:
          - fastsam:
              - model: reference/models/fastsam/model.md
              - predict: reference/models/fastsam/predict.md
              - prompt: reference/models/fastsam/prompt.md
              - utils: reference/models/fastsam/utils.md
              - val: reference/models/fastsam/val.md
          - nas:
              - model: reference/models/nas/model.md
              - predict: reference/models/nas/predict.md
              - val: reference/models/nas/val.md
          - rtdetr:
              - model: reference/models/rtdetr/model.md
              - predict: reference/models/rtdetr/predict.md
              - train: reference/models/rtdetr/train.md
              - val: reference/models/rtdetr/val.md
          - sam:
              - amg: reference/models/sam/amg.md
              - build: reference/models/sam/build.md
              - model: reference/models/sam/model.md
              - modules:
                  - decoders: reference/models/sam/modules/decoders.md
                  - encoders: reference/models/sam/modules/encoders.md
                  - sam: reference/models/sam/modules/sam.md
                  - tiny_encoder: reference/models/sam/modules/tiny_encoder.md
                  - transformer: reference/models/sam/modules/transformer.md
              - predict: reference/models/sam/predict.md
          - utils:
              - loss: reference/models/utils/loss.md
              - ops: reference/models/utils/ops.md
          - yolo:
              - classify:
                  - predict: reference/models/yolo/classify/predict.md
                  - train: reference/models/yolo/classify/train.md
                  - val: reference/models/yolo/classify/val.md
              - detect:
                  - predict: reference/models/yolo/detect/predict.md
                  - train: reference/models/yolo/detect/train.md
                  - val: reference/models/yolo/detect/val.md
              - model: reference/models/yolo/model.md
              - obb:
                  - predict: reference/models/yolo/obb/predict.md
                  - train: reference/models/yolo/obb/train.md
                  - val: reference/models/yolo/obb/val.md
              - pose:
                  - predict: reference/models/yolo/pose/predict.md
                  - train: reference/models/yolo/pose/train.md
                  - val: reference/models/yolo/pose/val.md
              - segment:
                  - predict: reference/models/yolo/segment/predict.md
                  - train: reference/models/yolo/segment/train.md
                  - val: reference/models/yolo/segment/val.md
      - nn:
          - autobackend: reference/nn/autobackend.md
          - modules:
              - block: reference/nn/modules/block.md
              - conv: reference/nn/modules/conv.md
              - head: reference/nn/modules/head.md
              - transformer: reference/nn/modules/transformer.md
              - utils: reference/nn/modules/utils.md
          - tasks: reference/nn/tasks.md
      - solutions:
          - ai_gym: reference/solutions/ai_gym.md
          - distance_calculation: reference/solutions/distance_calculation.md
          - heatmap: reference/solutions/heatmap.md
          - object_counter: reference/solutions/object_counter.md
          - speed_estimation: reference/solutions/speed_estimation.md
      - trackers:
          - basetrack: reference/trackers/basetrack.md
          - bot_sort: reference/trackers/bot_sort.md
          - byte_tracker: reference/trackers/byte_tracker.md
          - track: reference/trackers/track.md
          - utils:
              - gmc: reference/trackers/utils/gmc.md
              - kalman_filter: reference/trackers/utils/kalman_filter.md
              - matching: reference/trackers/utils/matching.md
      - utils:
          - __init__: reference/utils/__init__.md
          - autobatch: reference/utils/autobatch.md
          - benchmarks: reference/utils/benchmarks.md
          - callbacks:
              - base: reference/utils/callbacks/base.md
              - clearml: reference/utils/callbacks/clearml.md
              - comet: reference/utils/callbacks/comet.md
              - dvc: reference/utils/callbacks/dvc.md
              - hub: reference/utils/callbacks/hub.md
              - mlflow: reference/utils/callbacks/mlflow.md
              - neptune: reference/utils/callbacks/neptune.md
              - raytune: reference/utils/callbacks/raytune.md
              - tensorboard: reference/utils/callbacks/tensorboard.md
              - wb: reference/utils/callbacks/wb.md
          - checks: reference/utils/checks.md
          - dist: reference/utils/dist.md
          - downloads: reference/utils/downloads.md
          - errors: reference/utils/errors.md
          - files: reference/utils/files.md
          - instance: reference/utils/instance.md
          - loss: reference/utils/loss.md
          - metrics: reference/utils/metrics.md
          - ops: reference/utils/ops.md
          - patches: reference/utils/patches.md
          - plotting: reference/utils/plotting.md
          - tal: reference/utils/tal.md
          - torch_utils: reference/utils/torch_utils.md
          - triton: reference/utils/triton.md
          - tuner: reference/utils/tuner.md

  - Help:
      - Help: help/index.md
      - Frequently Asked Questions (FAQ): help/FAQ.md
      - Contributing Guide: help/contributing.md
      - Continuous Integration (CI) Guide: help/CI.md
      - Contributor License Agreement (CLA): help/CLA.md
      - Minimum Reproducible Example (MRE) Guide: help/minimum_reproducible_example.md
      - Code of Conduct: help/code_of_conduct.md
      - Environmental, Health and Safety (EHS) Policy: help/environmental-health-safety.md
      - Security Policy: help/security.md
      - Privacy Policy: help/privacy.md
